### ISSUE TITLE
Респонсив и недочеты

### ISSUE THREAD

**Issue by a-poluhin** [PsarewIvan/fsd#41]
Страница landing:
320px:
-) Тут у карточки не плохо бы добавить несколько пиксилей внутренних отступов, чтобы инпуты и текст не слипались с краями карточки.
![image](https://user-images.githubusercontent.com/10168007/117006494-b5708980-ad12-11eb-85e3-cfff67200dc0.png)

-) Бордер серый думаю можешь убрать мне кажется он особо не нужен, но это не критично=)
![image](https://user-images.githubusercontent.com/10168007/117008195-a985c700-ad14-11eb-8648-bf86228f5baa.png)

-) favicon не отображается на гитхаб пэйджах
![image](https://user-images.githubusercontent.com/10168007/117009982-86f4ad80-ad16-11eb-8820-d062a0d91475.png)

**Comment by PsarewIvan** [comment]
Мне сразу мержить ПР, или после проверки?
