### ISSUE TITLE
Code style(best practice)

### ISSUE THREAD

**Issue by a-poluhin** [PsarewIvan/fsd#43]
Все кавычки в pug(html) должны быть двойными, а в js и css одинарными.
![image](https://user-images.githubusercontent.com/10168007/117013980-8eb65100-ad1a-11eb-8aa7-7524f9ca90c1.png)

**Comment by PsarewIvan** [comment]
Немного ошибся с первым ПР, отщепил его не от мастера, а от предыдущей ветки :)

Кавычки все поправил, НО:
- оставил двойные кавычки в scss файлах где в `background-image`  инлайном прописываю svg. Просто в самом svg прописаны одинарные кавычки.

Если это считается как ошибка - исправлю

**Comment by PsarewIvan** [comment]
Вот типо такого:
<img width="593" alt="Screenshot 2021-05-05 at 19 57 07" src="https://user-images.githubusercontent.com/28845333/117179811-347dc480-addc-11eb-9fe1-4c82546696c3.png">

**Comment by a-poluhin** [comment]
> Вот типо такого:
> <img alt="Screenshot 2021-05-05 at 19 57 07" width="593" src="https://user-images.githubusercontent.com/28845333/117179811-347dc480-addc-11eb-9fe1-4c82546696c3.png">

По идее можно сделать одинарные снаружи а двойные внутри
